package main

import (
	"github.com/aws-organizations/mcp-server/config"
	"github.com/aws-organizations/mcp-server/models"
	tools_x_amz_target_awsorganizationsv20161128_updateorganizationalunit "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_updateorganizationalunit"
	tools_x_amz_target_awsorganizationsv20161128_deletepolicy "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_deletepolicy"
	tools_x_amz_target_awsorganizationsv20161128_enablepolicytype "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_enablepolicytype"
	tools_x_amz_target_awsorganizationsv20161128_tagresource "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_tagresource"
	tools_x_amz_target_awsorganizationsv20161128_listorganizationalunitsforparent "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_listorganizationalunitsforparent"
	tools_x_amz_target_awsorganizationsv20161128_enableawsserviceaccess "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_enableawsserviceaccess"
	tools_x_amz_target_awsorganizationsv20161128_describehandshake "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_describehandshake"
	tools_x_amz_target_awsorganizationsv20161128_removeaccountfromorganization "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_removeaccountfromorganization"
	tools_x_amz_target_awsorganizationsv20161128_listpolicies "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_listpolicies"
	tools_x_amz_target_awsorganizationsv20161128_registerdelegatedadministrator "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_registerdelegatedadministrator"
	tools_x_amz_target_awsorganizationsv20161128_listaccountsforparent "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_listaccountsforparent"
	tools_x_amz_target_awsorganizationsv20161128_closeaccount "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_closeaccount"
	tools_x_amz_target_awsorganizationsv20161128_deleteorganizationalunit "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_deleteorganizationalunit"
	tools_x_amz_target_awsorganizationsv20161128_deregisterdelegatedadministrator "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_deregisterdelegatedadministrator"
	tools_x_amz_target_awsorganizationsv20161128_putresourcepolicy "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_putresourcepolicy"
	tools_x_amz_target_awsorganizationsv20161128_inviteaccounttoorganization "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_inviteaccounttoorganization"
	tools_x_amz_target_awsorganizationsv20161128_updatepolicy "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_updatepolicy"
	tools_x_amz_target_awsorganizationsv20161128_describeaccount "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_describeaccount"
	tools_x_amz_target_awsorganizationsv20161128_listtagsforresource "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_listtagsforresource"
	tools_x_amz_target_awsorganizationsv20161128_detachpolicy "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_detachpolicy"
	tools_x_amz_target_awsorganizationsv20161128_createorganizationalunit "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_createorganizationalunit"
	tools_x_amz_target_awsorganizationsv20161128_deleteorganization "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_deleteorganization"
	tools_x_amz_target_awsorganizationsv20161128_listroots "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_listroots"
	tools_x_amz_target_awsorganizationsv20161128_describeresourcepolicy "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_describeresourcepolicy"
	tools_x_amz_target_awsorganizationsv20161128_listdelegatedservicesforaccount "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_listdelegatedservicesforaccount"
	tools_x_amz_target_awsorganizationsv20161128_createaccount "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_createaccount"
	tools_x_amz_target_awsorganizationsv20161128_declinehandshake "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_declinehandshake"
	tools_x_amz_target_awsorganizationsv20161128_listdelegatedadministrators "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_listdelegatedadministrators"
	tools_x_amz_target_awsorganizationsv20161128_attachpolicy "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_attachpolicy"
	tools_x_amz_target_awsorganizationsv20161128_listchildren "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_listchildren"
	tools_x_amz_target_awsorganizationsv20161128_accepthandshake "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_accepthandshake"
	tools_x_amz_target_awsorganizationsv20161128_disableawsserviceaccess "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_disableawsserviceaccess"
	tools_x_amz_target_awsorganizationsv20161128_describepolicy "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_describepolicy"
	tools_x_amz_target_awsorganizationsv20161128_enableallfeatures "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_enableallfeatures"
	tools_x_amz_target_awsorganizationsv20161128_moveaccount "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_moveaccount"
	tools_x_amz_target_awsorganizationsv20161128_cancelhandshake "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_cancelhandshake"
	tools_x_amz_target_awsorganizationsv20161128_untagresource "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_untagresource"
	tools_x_amz_target_awsorganizationsv20161128_listawsserviceaccessfororganization "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_listawsserviceaccessfororganization"
	tools_x_amz_target_awsorganizationsv20161128_leaveorganization "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_leaveorganization"
	tools_x_amz_target_awsorganizationsv20161128_listaccounts "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_listaccounts"
	tools_x_amz_target_awsorganizationsv20161128_listpoliciesfortarget "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_listpoliciesfortarget"
	tools_x_amz_target_awsorganizationsv20161128_createpolicy "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_createpolicy"
	tools_x_amz_target_awsorganizationsv20161128_describeeffectivepolicy "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_describeeffectivepolicy"
	tools_x_amz_target_awsorganizationsv20161128_deleteresourcepolicy "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_deleteresourcepolicy"
	tools_x_amz_target_awsorganizationsv20161128_describecreateaccountstatus "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_describecreateaccountstatus"
	tools_x_amz_target_awsorganizationsv20161128_describeorganizationalunit "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_describeorganizationalunit"
	tools_x_amz_target_awsorganizationsv20161128_disablepolicytype "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_disablepolicytype"
	tools_x_amz_target_awsorganizationsv20161128_creategovcloudaccount "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_creategovcloudaccount"
	tools_x_amz_target_awsorganizationsv20161128_listcreateaccountstatus "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_listcreateaccountstatus"
	tools_x_amz_target_awsorganizationsv20161128_listtargetsforpolicy "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_listtargetsforpolicy"
	tools_x_amz_target_awsorganizationsv20161128_createorganization "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_createorganization"
	tools_x_amz_target_awsorganizationsv20161128_listhandshakesforaccount "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_listhandshakesforaccount"
	tools_x_amz_target_awsorganizationsv20161128_listhandshakesfororganization "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_listhandshakesfororganization"
	tools_x_amz_target_awsorganizationsv20161128_describeorganization "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_describeorganization"
	tools_x_amz_target_awsorganizationsv20161128_listparents "github.com/aws-organizations/mcp-server/tools/x_amz_target_awsorganizationsv20161128_listparents"
)

func GetAll(cfg *config.APIConfig) []models.Tool {
	return []models.Tool{
		tools_x_amz_target_awsorganizationsv20161128_updateorganizationalunit.CreateUpdateorganizationalunitTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_deletepolicy.CreateDeletepolicyTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_enablepolicytype.CreateEnablepolicytypeTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_tagresource.CreateTagresourceTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_listorganizationalunitsforparent.CreateListorganizationalunitsforparentTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_enableawsserviceaccess.CreateEnableawsserviceaccessTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_describehandshake.CreateDescribehandshakeTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_removeaccountfromorganization.CreateRemoveaccountfromorganizationTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_listpolicies.CreateListpoliciesTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_registerdelegatedadministrator.CreateRegisterdelegatedadministratorTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_listaccountsforparent.CreateListaccountsforparentTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_closeaccount.CreateCloseaccountTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_deleteorganizationalunit.CreateDeleteorganizationalunitTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_deregisterdelegatedadministrator.CreateDeregisterdelegatedadministratorTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_putresourcepolicy.CreatePutresourcepolicyTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_inviteaccounttoorganization.CreateInviteaccounttoorganizationTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_updatepolicy.CreateUpdatepolicyTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_describeaccount.CreateDescribeaccountTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_listtagsforresource.CreateListtagsforresourceTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_detachpolicy.CreateDetachpolicyTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_createorganizationalunit.CreateCreateorganizationalunitTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_deleteorganization.CreateDeleteorganizationTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_listroots.CreateListrootsTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_describeresourcepolicy.CreateDescriberesourcepolicyTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_listdelegatedservicesforaccount.CreateListdelegatedservicesforaccountTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_createaccount.CreateCreateaccountTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_declinehandshake.CreateDeclinehandshakeTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_listdelegatedadministrators.CreateListdelegatedadministratorsTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_attachpolicy.CreateAttachpolicyTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_listchildren.CreateListchildrenTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_accepthandshake.CreateAccepthandshakeTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_disableawsserviceaccess.CreateDisableawsserviceaccessTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_describepolicy.CreateDescribepolicyTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_enableallfeatures.CreateEnableallfeaturesTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_moveaccount.CreateMoveaccountTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_cancelhandshake.CreateCancelhandshakeTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_untagresource.CreateUntagresourceTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_listawsserviceaccessfororganization.CreateListawsserviceaccessfororganizationTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_leaveorganization.CreateLeaveorganizationTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_listaccounts.CreateListaccountsTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_listpoliciesfortarget.CreateListpoliciesfortargetTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_createpolicy.CreateCreatepolicyTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_describeeffectivepolicy.CreateDescribeeffectivepolicyTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_deleteresourcepolicy.CreateDeleteresourcepolicyTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_describecreateaccountstatus.CreateDescribecreateaccountstatusTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_describeorganizationalunit.CreateDescribeorganizationalunitTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_disablepolicytype.CreateDisablepolicytypeTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_creategovcloudaccount.CreateCreategovcloudaccountTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_listcreateaccountstatus.CreateListcreateaccountstatusTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_listtargetsforpolicy.CreateListtargetsforpolicyTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_createorganization.CreateCreateorganizationTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_listhandshakesforaccount.CreateListhandshakesforaccountTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_listhandshakesfororganization.CreateListhandshakesfororganizationTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_describeorganization.CreateDescribeorganizationTool(cfg),
		tools_x_amz_target_awsorganizationsv20161128_listparents.CreateListparentsTool(cfg),
	}
}
